// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct EventsLatestArgs: ConvexCodable, Sendable {
    let actorId: String
}


struct EventsPublishArgs: ConvexCodable, Sendable {
    let payload: EventPayload
}


struct EventDoc: ConvexCodable, Sendable {
    let actorId: String
    let payload: EventPayload
}


struct EventPayloadCreated: ConvexCodable, Sendable {
    let kind: String
    let targetId: String
}


struct EventPayloadDeleted: ConvexCodable, Sendable {
    let kind: String
    let reason: String?
    let targetId: String
}


enum EventPayload: ConvexCodable, Sendable {
    case created(EventPayloadCreated)
    case deleted(EventPayloadDeleted)

    private enum CodingKeys: String, CodingKey {
        case kind
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let tag = try container.decode(String.self, forKey: .kind)
        switch tag {
        case "created":
            self = .created(try EventPayloadCreated(from: decoder))
        case "deleted":
            self = .deleted(try EventPayloadDeleted(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(forKey: .kind, in: container, debugDescription: "Invalid discriminator value")
        }
    }

    func encode(to encoder: Encoder) throws {
        switch self {
        case .created(let value):
            try value.encode(to: encoder)
        case .deleted(let value):
            try value.encode(to: encoder)
        }
    }
}


typealias EventsLatestReturn = Event?

typealias EventsPublishReturn = String

struct Event: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let actorId: String
    let payload: EventPayload

    var id: String { _id }
}


extension EventsLatestArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["actorId"] = actorId
        return args
    }
}


extension EventsPublishArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["payload"] = payload
        return args
    }
}


