// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct UsersByEmailArgs: ConvexCodable, Sendable {
    let email: String
}


enum UsersCreateArgsStatus: String, ConvexCodable, Sendable {
    case active = "active"
    case disabled = "disabled"
}


struct UsersCreateArgs: ConvexCodable, Sendable {
    let email: String
    let status: UsersCreateArgsStatus
}


typealias UsersByEmailReturn = User?

typealias UsersCreateReturn = String

enum UserStatus: String, ConvexCodable, Sendable {
    case active = "active"
    case disabled = "disabled"
}


struct User: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let email: String
    let status: UserStatus

    var id: String { _id }
}


extension UsersByEmailArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["email"] = email
        return args
    }
}


extension UsersCreateArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["email"] = email
        args["status"] = status
        return args
    }
}


