// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct StatusLogsGetArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
}


struct StatusLogsPutArgs: ConvexCodable, Sendable {
    let `internal`: Bool
    let type: String
}


typealias StatusLogsGetReturn = StatusLog?

typealias StatusLogsPutReturn = String

struct StatusLog: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let `internal`: Bool
    let mixedCaseName: String
    let snakeCase: String
    let type: String

    private enum CodingKeys: String, CodingKey {
        case _id
        case `internal`
        case mixedCaseName
        case snakeCase = "snake_case"
        case type
    }

    var id: String { _id }
}


extension StatusLogsGetArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        return args
    }
}


extension StatusLogsPutArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["internal"] = `internal`
        args["type"] = type
        return args
    }
}


