// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn admin_users_list(
        client: &ConvexClient,
        args: &AdminUsersListArgs,
    ) -> Result<AdminUsersListReturn, ConvexError> {
        client.query("admin/users:list", args).await
    }

    pub async fn public_users_list(
        client: &ConvexClient,
        args: &PublicUsersListArgs,
    ) -> Result<PublicUsersListReturn, ConvexError> {
        client.query("public/users:list", args).await
    }

}

pub mod mutations {
    use super::*;

}

pub mod actions {
    use super::*;

}
