// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn things_list(
        client: &ConvexClient,
        args: &ThingsListArgs,
    ) -> Result<ThingsListReturn, ConvexError> {
        client.query("things:list", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn things_create(
        client: &ConvexClient,
        args: &ThingsCreateArgs,
    ) -> Result<ThingsCreateReturn, ConvexError> {
        client.mutation("things:create", args).await
    }

}

pub mod actions {
    use super::*;

    pub async fn things_inspect(
        client: &ConvexClient,
        args: &ThingsInspectArgs,
    ) -> Result<ThingsInspectReturn, ConvexError> {
        client.action("things:inspect", args).await
    }

}
