// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn users_by_email(
        client: &ConvexClient,
        args: &UsersByEmailArgs,
    ) -> Result<UsersByEmailReturn, ConvexError> {
        client.query("users:byEmail", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn users_create(
        client: &ConvexClient,
        args: &UsersCreateArgs,
    ) -> Result<UsersCreateReturn, ConvexError> {
        client.mutation("users:create", args).await
    }

}

pub mod actions {
    use super::*;

}
