// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn jobs_snapshot(
        client: &ConvexClient,
        args: &JobsSnapshotArgs,
    ) -> Result<JobsSnapshotReturn, ConvexError> {
        client.query("jobs:snapshot", args).await
    }

    pub async fn jobs_stream(
        client: &ConvexClient,
        args: &JobsStreamArgs,
    ) -> Result<JobsStreamReturn, ConvexError> {
        client.query("jobs:stream", args).await
    }

}

pub mod mutations {
    use super::*;

}

pub mod actions {
    use super::*;

}
