// This file is @generated by hull. DO NOT EDIT.
#![allow(non_snake_case)]
#![allow(clippy::disallowed_types)]
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::collections::{BTreeMap, HashMap};
use crate::convex::ConvexValue;

#[derive(Debug, Clone)]
pub struct ConvexTypeError {
    message: String,
}
impl ConvexTypeError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
impl std::fmt::Display for ConvexTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
impl std::error::Error for ConvexTypeError {}

pub trait ConvexEncode {
    fn to_convex_value(&self) -> ConvexValue;
}

mod sealed {
    pub trait Sealed {}
}

pub trait ConvexArgs: sealed::Sealed + ConvexEncode {}
impl<T> ConvexArgs for T
where
    T: sealed::Sealed + ConvexEncode,
{}

pub trait JsonValidate: Sized {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError>;
    fn parse_json(value: &JsonValue) -> Result<Self, ConvexTypeError>
    where
        Self: for<'de> Deserialize<'de>,
    {
        Self::validate_json(value)?;
        serde_json::from_value(value.clone())
            .map_err(|err| ConvexTypeError::new(err.to_string()))
    }
}

fn json_value_to_convex(value: &JsonValue) -> ConvexValue {
    match value {
        JsonValue::Null => ConvexValue::Null,
        JsonValue::Bool(value) => ConvexValue::Bool(*value),
        JsonValue::Number(value) => ConvexValue::Float(value.as_f64().unwrap_or(0.0)),
        JsonValue::String(value) => ConvexValue::String(value.clone()),
        JsonValue::Array(values) => {
            ConvexValue::Array(values.iter().map(json_value_to_convex).collect())
        }
        JsonValue::Object(values) => ConvexValue::Object(
            values
                .iter()
                .map(|(key, value)| (key.clone(), json_value_to_convex(value)))
                .collect(),
        ),
    }
}

impl ConvexEncode for String {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::String(self.clone())
    }
}
impl ConvexEncode for bool {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Bool(*self)
    }
}
impl ConvexEncode for f64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Float(*self)
    }
}
impl ConvexEncode for i64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Int(*self)
    }
}
impl ConvexEncode for () {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Null
    }
}
impl ConvexEncode for JsonValue {
    fn to_convex_value(&self) -> ConvexValue {
        json_value_to_convex(self)
    }
}
impl<T> ConvexEncode for Option<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            Some(value) => value.to_convex_value(),
            None => ConvexValue::Null,
        }
    }
}
impl<T> ConvexEncode for Vec<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Array(self.iter().map(ConvexEncode::to_convex_value).collect())
    }
}
impl<T> ConvexEncode for HashMap<String, T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        for (key, value) in self {
            map.insert(key.clone(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl JsonValidate for String {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_string() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected string"))
        }
    }
}
impl JsonValidate for bool {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_boolean() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected bool"))
        }
    }
}
impl JsonValidate for f64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_number() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected number"))
        }
    }
}
impl JsonValidate for i64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.as_i64().is_some() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected int64"))
        }
    }
}
impl JsonValidate for () {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected null"))
        }
    }
}
impl JsonValidate for JsonValue {
    fn validate_json(_value: &JsonValue) -> Result<(), ConvexTypeError> {
        Ok(())
    }
}
impl<T> JsonValidate for Option<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            T::validate_json(value)
        }
    }
}
impl<T> JsonValidate for Vec<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let array = value
            .as_array()
            .ok_or_else(|| ConvexTypeError::new("expected array"))?;
        for item in array {
            T::validate_json(item)?;
        }
        Ok(())
    }
}
impl<T> JsonValidate for HashMap<String, T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for item in object.values() {
            T::validate_json(item)?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct JobsSnapshotArgs {
    pub id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct JobsStreamArgs {
    pub id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Job {
    pub _id: String,
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    pub title: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum JobsSnapshotReturnState {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct JobsSnapshotReturn {
    pub job: Job,
    pub progress: Option<f64>,
    pub state: JobsSnapshotReturnState,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct JobsStreamReturnObjectPayload {
    #[serde(rename = "idsByOwner")]
    pub ids_by_owner: HashMap<String, String>,
    pub items: Vec<Job>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct JobsStreamReturnObject {
    pub kind: String,
    pub payload: JobsStreamReturnObjectPayload,
}

pub type JobsStreamReturn = Option<JobsStreamReturnObject>;
impl ConvexEncode for JobsSnapshotArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("id".to_string(), self.id.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for JobsStreamArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("id".to_string(), self.id.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for Job {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("_id".to_string(), self._id.to_convex_value());
        map.insert("ownerId".to_string(), self.owner_id.to_convex_value());
        map.insert("title".to_string(), self.title.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for JobsSnapshotReturnState {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            JobsSnapshotReturnState::Queued => ConvexValue::String("queued".to_string()),
            JobsSnapshotReturnState::Running => ConvexValue::String("running".to_string()),
            JobsSnapshotReturnState::Failed => ConvexValue::String("failed".to_string()),
        }
    }
}

impl ConvexEncode for JobsSnapshotReturn {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("job".to_string(), self.job.to_convex_value());
        if let Some(value) = &self.progress {
            map.insert("progress".to_string(), value.to_convex_value());
        }
        map.insert("state".to_string(), self.state.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for JobsStreamReturnObjectPayload {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("idsByOwner".to_string(), self.ids_by_owner.to_convex_value());
        map.insert("items".to_string(), self.items.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for JobsStreamReturnObject {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("kind".to_string(), self.kind.to_convex_value());
        map.insert("payload".to_string(), self.payload.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl sealed::Sealed for JobsSnapshotArgs {}

impl sealed::Sealed for JobsStreamArgs {}

impl JsonValidate for JobsSnapshotArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "id" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: id"));
        }
        Ok(())
    }
}

impl JsonValidate for JobsStreamArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "id" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: id"));
        }
        Ok(())
    }
}

impl JsonValidate for Job {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "_id" => {}
                "ownerId" => {}
                "title" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("_id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: _id"));
        }
        if let Some(field_value) = object.get("ownerId") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: ownerId"));
        }
        if let Some(field_value) = object.get("title") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: title"));
        }
        Ok(())
    }
}

impl JsonValidate for JobsSnapshotReturnState {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let value = value.as_str().ok_or_else(|| ConvexTypeError::new("expected string"))?;
        match value {
            "queued" => Ok(()),
            "running" => Ok(()),
            "failed" => Ok(()),
            _ => Err(ConvexTypeError::new("invalid enum value")),
        }
    }
}

impl JsonValidate for JobsSnapshotReturn {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "job" => {}
                "progress" => {}
                "state" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("job") {
            <Job as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: job"));
        }
        if let Some(field_value) = object.get("progress") {
            if field_value.is_null() {
                return Err(ConvexTypeError::new("optional field 'progress' must be omitted, not null"));
            }
            <f64 as JsonValidate>::validate_json(field_value)?;
        }
        if let Some(field_value) = object.get("state") {
            <JobsSnapshotReturnState as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: state"));
        }
        Ok(())
    }
}

impl JsonValidate for JobsStreamReturnObjectPayload {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "idsByOwner" => {}
                "items" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("idsByOwner") {
            <HashMap<String, String> as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: idsByOwner"));
        }
        if let Some(field_value) = object.get("items") {
            <Vec<Job> as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: items"));
        }
        Ok(())
    }
}

impl JsonValidate for JobsStreamReturnObject {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "kind" => {}
                "payload" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("kind") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: kind"));
        }
        if let Some(field_value) = object.get("payload") {
            <JobsStreamReturnObjectPayload as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: payload"));
        }
        Ok(())
    }
}

