// This file is @generated by hull. DO NOT EDIT.
#![allow(non_snake_case)]
#![allow(clippy::disallowed_types)]
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::collections::{BTreeMap, HashMap};
use crate::convex::ConvexValue;

#[derive(Debug, Clone)]
pub struct ConvexTypeError {
    message: String,
}
impl ConvexTypeError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
impl std::fmt::Display for ConvexTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
impl std::error::Error for ConvexTypeError {}

pub trait ConvexEncode {
    fn to_convex_value(&self) -> ConvexValue;
}

mod sealed {
    pub trait Sealed {}
}

pub trait ConvexArgs: sealed::Sealed + ConvexEncode {}
impl<T> ConvexArgs for T
where
    T: sealed::Sealed + ConvexEncode,
{}

pub trait JsonValidate: Sized {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError>;
    fn parse_json(value: &JsonValue) -> Result<Self, ConvexTypeError>
    where
        Self: for<'de> Deserialize<'de>,
    {
        Self::validate_json(value)?;
        serde_json::from_value(value.clone())
            .map_err(|err| ConvexTypeError::new(err.to_string()))
    }
}

fn json_value_to_convex(value: &JsonValue) -> ConvexValue {
    match value {
        JsonValue::Null => ConvexValue::Null,
        JsonValue::Bool(value) => ConvexValue::Bool(*value),
        JsonValue::Number(value) => ConvexValue::Float(value.as_f64().unwrap_or(0.0)),
        JsonValue::String(value) => ConvexValue::String(value.clone()),
        JsonValue::Array(values) => {
            ConvexValue::Array(values.iter().map(json_value_to_convex).collect())
        }
        JsonValue::Object(values) => ConvexValue::Object(
            values
                .iter()
                .map(|(key, value)| (key.clone(), json_value_to_convex(value)))
                .collect(),
        ),
    }
}

impl ConvexEncode for String {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::String(self.clone())
    }
}
impl ConvexEncode for bool {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Bool(*self)
    }
}
impl ConvexEncode for f64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Float(*self)
    }
}
impl ConvexEncode for i64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Int(*self)
    }
}
impl ConvexEncode for () {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Null
    }
}
impl ConvexEncode for JsonValue {
    fn to_convex_value(&self) -> ConvexValue {
        json_value_to_convex(self)
    }
}
impl<T> ConvexEncode for Option<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            Some(value) => value.to_convex_value(),
            None => ConvexValue::Null,
        }
    }
}
impl<T> ConvexEncode for Vec<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Array(self.iter().map(ConvexEncode::to_convex_value).collect())
    }
}
impl<T> ConvexEncode for HashMap<String, T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        for (key, value) in self {
            map.insert(key.clone(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl JsonValidate for String {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_string() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected string"))
        }
    }
}
impl JsonValidate for bool {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_boolean() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected bool"))
        }
    }
}
impl JsonValidate for f64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_number() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected number"))
        }
    }
}
impl JsonValidate for i64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.as_i64().is_some() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected int64"))
        }
    }
}
impl JsonValidate for () {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected null"))
        }
    }
}
impl JsonValidate for JsonValue {
    fn validate_json(_value: &JsonValue) -> Result<(), ConvexTypeError> {
        Ok(())
    }
}
impl<T> JsonValidate for Option<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            T::validate_json(value)
        }
    }
}
impl<T> JsonValidate for Vec<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let array = value
            .as_array()
            .ok_or_else(|| ConvexTypeError::new("expected array"))?;
        for item in array {
            T::validate_json(item)?;
        }
        Ok(())
    }
}
impl<T> JsonValidate for HashMap<String, T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for item in object.values() {
            T::validate_json(item)?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AICorrectStreamArgs {
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BillingStripeWebhookArgs {
}

pub type AICorrectStreamReturn = JsonValue;
pub type BillingStripeWebhookReturn = JsonValue;
impl ConvexEncode for AICorrectStreamArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let map = BTreeMap::new();
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for BillingStripeWebhookArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let map = BTreeMap::new();
        ConvexValue::Object(map)
    }
}

impl sealed::Sealed for AICorrectStreamArgs {}

impl sealed::Sealed for BillingStripeWebhookArgs {}

impl JsonValidate for AICorrectStreamArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        if let Some(key) = object.keys().next() {
            return Err(ConvexTypeError::new(format!("unknown field: {}", key)));
        }
        Ok(())
    }
}

impl JsonValidate for BillingStripeWebhookArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        if let Some(key) = object.keys().next() {
            return Err(ConvexTypeError::new(format!("unknown field: {}", key)));
        }
        Ok(())
    }
}

