// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn posts_get_by_id(
        client: &ConvexClient,
        args: &PostsGetByIDArgs,
    ) -> Result<PostsGetByIDReturn, ConvexError> {
        client.query("posts:getById", args).await
    }

    pub async fn posts_list_by_author(
        client: &ConvexClient,
        args: &PostsListByAuthorArgs,
    ) -> Result<PostsListByAuthorReturn, ConvexError> {
        client.query("posts:listByAuthor", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn posts_create(
        client: &ConvexClient,
        args: &PostsCreateArgs,
    ) -> Result<PostsCreateReturn, ConvexError> {
        client.mutation("posts:create", args).await
    }

}

pub mod actions {
    use super::*;

}
