// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn status_logs_get(
        client: &ConvexClient,
        args: &StatusLogsGetArgs,
    ) -> Result<StatusLogsGetReturn, ConvexError> {
        client.query("statusLogs:get", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn status_logs_put(
        client: &ConvexClient,
        args: &StatusLogsPutArgs,
    ) -> Result<StatusLogsPutReturn, ConvexError> {
        client.mutation("statusLogs:put", args).await
    }

}

pub mod actions {
    use super::*;

}
