// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct JobsSnapshotArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
}


struct JobsStreamArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
}


struct Job: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let ownerId: String
    let title: String

    var id: String { _id }
}


enum JobsSnapshotReturnState: String, ConvexCodable, Sendable {
    case queued = "queued"
    case running = "running"
    case failed = "failed"
}


struct JobsSnapshotReturn: ConvexCodable, Sendable {
    let job: Job
    let progress: Double?
    let state: JobsSnapshotReturnState
}


struct JobsStreamReturnObjectPayload: ConvexCodable, Sendable {
    let idsByOwner: [String: String]
    let items: [Job]
}


struct JobsStreamReturnObject: ConvexCodable, Sendable {
    let kind: String
    let payload: JobsStreamReturnObjectPayload
}


typealias JobsStreamReturn = JobsStreamReturnObject?

extension JobsSnapshotArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        return args
    }
}


extension JobsStreamArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        return args
    }
}


