// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct AICorrectStreamArgs: ConvexCodable, Sendable {
}


struct BillingStripeWebhookArgs: ConvexCodable, Sendable {
}


typealias AICorrectStreamReturn = JSONValue

typealias BillingStripeWebhookReturn = JSONValue

extension AICorrectStreamArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        let args: [String: ConvexEncodable?] = [:]
        return args
    }
}


extension BillingStripeWebhookArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        let args: [String: ConvexEncodable?] = [:]
        return args
    }
}


