// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct PostsCreateArgs: ConvexCodable, Sendable {
    let authorId: String
    let body: String
}


struct PostsGetByIDArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
}


struct PostsListByAuthorArgs: ConvexCodable, Sendable {
    let authorId: String
}


struct Post: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let authorId: String
    let body: String

    var id: String { _id }
}


typealias PostsCreateReturn = String

typealias PostsGetByIDReturn = Post?

typealias PostsListByAuthorReturn = [Post]

struct User: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let name: String

    var id: String { _id }
}


extension PostsGetByIDArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        return args
    }
}


extension PostsListByAuthorArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["authorId"] = authorId
        return args
    }
}


extension PostsCreateArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["authorId"] = authorId
        args["body"] = body
        return args
    }
}


