// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct ThingsCreateArgsItem: ConvexCodable, Sendable {
    let count: Double
    let title: String
}


struct ThingsCreateArgs: ConvexCodable, Sendable {
    let item: ThingsCreateArgsItem
}


struct ThingsInspectArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
}


struct ThingsListArgs: ConvexCodable, Sendable {
    let cursor: String?
    let includeGone: Bool?
}


enum PrimitiveThingStatus: String, ConvexCodable, Sendable {
    case ok = "ok"
    case bad = "bad"
}


struct PrimitiveThing: ConvexCodable, Sendable {
    let anything: JSONValue
    let count: Double
    let enabled: Bool
    let gone: JSONValue
    let maybeNote: String?
    let maybeRef: String?
    let metrics: [String: Double]
    let ratio: Double
    let role: String
    let score: Double
    let status: PrimitiveThingStatus
    let summary: String?
    let tags: [String]
    let title: String
    @ConvexInt var visits: Int64

    private enum CodingKeys: String, CodingKey {
        case anything
        case count
        case enabled
        case gone
        case maybeNote
        case maybeRef
        case metrics
        case ratio
        case role
        case score
        case status
        case summary
        case tags
        case title
        case visits
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(anything, forKey: .anything)
        try container.encode(count, forKey: .count)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(gone, forKey: .gone)
        try container.encodeIfPresent(maybeNote, forKey: .maybeNote)
        try container.encodeIfPresent(maybeRef, forKey: .maybeRef)
        try container.encode(metrics, forKey: .metrics)
        try container.encode(ratio, forKey: .ratio)
        try container.encode(role, forKey: .role)
        try container.encode(score, forKey: .score)
        try container.encode(status, forKey: .status)
        if let value = summary {
            try container.encode(value, forKey: .summary)
        } else {
            try container.encodeNil(forKey: .summary)
        }
        try container.encode(tags, forKey: .tags)
        try container.encode(title, forKey: .title)
        try container.encode(visits, forKey: .visits)
    }
}


typealias ThingsCreateReturn = String

typealias ThingsInspectReturn = Thing?

typealias ThingsListReturn = [Thing]

enum ThingStatus: String, ConvexCodable, Sendable {
    case ok = "ok"
    case bad = "bad"
}


struct Thing: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let anything: JSONValue
    let count: Double
    let enabled: Bool
    let gone: JSONValue
    let maybeNote: String?
    let maybeRef: String?
    let metrics: [String: Double]
    let ratio: Double
    let role: String
    let score: Double
    let status: ThingStatus
    let summary: String?
    let tags: [String]
    let title: String
    @ConvexInt var visits: Int64

    private enum CodingKeys: String, CodingKey {
        case _id
        case anything
        case count
        case enabled
        case gone
        case maybeNote
        case maybeRef
        case metrics
        case ratio
        case role
        case score
        case status
        case summary
        case tags
        case title
        case visits
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_id, forKey: ._id)
        try container.encode(anything, forKey: .anything)
        try container.encode(count, forKey: .count)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(gone, forKey: .gone)
        try container.encodeIfPresent(maybeNote, forKey: .maybeNote)
        try container.encodeIfPresent(maybeRef, forKey: .maybeRef)
        try container.encode(metrics, forKey: .metrics)
        try container.encode(ratio, forKey: .ratio)
        try container.encode(role, forKey: .role)
        try container.encode(score, forKey: .score)
        try container.encode(status, forKey: .status)
        if let value = summary {
            try container.encode(value, forKey: .summary)
        } else {
            try container.encodeNil(forKey: .summary)
        }
        try container.encode(tags, forKey: .tags)
        try container.encode(title, forKey: .title)
        try container.encode(visits, forKey: .visits)
    }

    var id: String { _id }
}


extension ThingsListArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        if let value = cursor {
            args["cursor"] = value
        }
        if let value = includeGone {
            args["includeGone"] = value
        }
        return args
    }
}


extension ThingsCreateArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["item"] = item
        return args
    }
}


extension ThingsInspectArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        return args
    }
}


