// This file is @generated by hull. DO NOT EDIT.
#![allow(non_snake_case)]
#![allow(clippy::disallowed_types)]
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::collections::{BTreeMap, HashMap};
use crate::convex::ConvexValue;

#[derive(Debug, Clone)]
pub struct ConvexTypeError {
    message: String,
}
impl ConvexTypeError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
impl std::fmt::Display for ConvexTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
impl std::error::Error for ConvexTypeError {}

pub trait ConvexEncode {
    fn to_convex_value(&self) -> ConvexValue;
}

mod sealed {
    pub trait Sealed {}
}

pub trait ConvexArgs: sealed::Sealed + ConvexEncode {}
impl<T> ConvexArgs for T
where
    T: sealed::Sealed + ConvexEncode,
{}

pub trait JsonValidate: Sized {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError>;
    fn parse_json(value: &JsonValue) -> Result<Self, ConvexTypeError>
    where
        Self: for<'de> Deserialize<'de>,
    {
        Self::validate_json(value)?;
        serde_json::from_value(value.clone())
            .map_err(|err| ConvexTypeError::new(err.to_string()))
    }
}

fn json_value_to_convex(value: &JsonValue) -> ConvexValue {
    match value {
        JsonValue::Null => ConvexValue::Null,
        JsonValue::Bool(value) => ConvexValue::Bool(*value),
        JsonValue::Number(value) => ConvexValue::Float(value.as_f64().unwrap_or(0.0)),
        JsonValue::String(value) => ConvexValue::String(value.clone()),
        JsonValue::Array(values) => {
            ConvexValue::Array(values.iter().map(json_value_to_convex).collect())
        }
        JsonValue::Object(values) => ConvexValue::Object(
            values
                .iter()
                .map(|(key, value)| (key.clone(), json_value_to_convex(value)))
                .collect(),
        ),
    }
}

impl ConvexEncode for String {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::String(self.clone())
    }
}
impl ConvexEncode for bool {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Bool(*self)
    }
}
impl ConvexEncode for f64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Float(*self)
    }
}
impl ConvexEncode for i64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Int(*self)
    }
}
impl ConvexEncode for () {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Null
    }
}
impl ConvexEncode for JsonValue {
    fn to_convex_value(&self) -> ConvexValue {
        json_value_to_convex(self)
    }
}
impl<T> ConvexEncode for Option<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            Some(value) => value.to_convex_value(),
            None => ConvexValue::Null,
        }
    }
}
impl<T> ConvexEncode for Vec<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Array(self.iter().map(ConvexEncode::to_convex_value).collect())
    }
}
impl<T> ConvexEncode for HashMap<String, T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        for (key, value) in self {
            map.insert(key.clone(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl JsonValidate for String {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_string() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected string"))
        }
    }
}
impl JsonValidate for bool {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_boolean() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected bool"))
        }
    }
}
impl JsonValidate for f64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_number() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected number"))
        }
    }
}
impl JsonValidate for i64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.as_i64().is_some() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected int64"))
        }
    }
}
impl JsonValidate for () {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected null"))
        }
    }
}
impl JsonValidate for JsonValue {
    fn validate_json(_value: &JsonValue) -> Result<(), ConvexTypeError> {
        Ok(())
    }
}
impl<T> JsonValidate for Option<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            T::validate_json(value)
        }
    }
}
impl<T> JsonValidate for Vec<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let array = value
            .as_array()
            .ok_or_else(|| ConvexTypeError::new("expected array"))?;
        for item in array {
            T::validate_json(item)?;
        }
        Ok(())
    }
}
impl<T> JsonValidate for HashMap<String, T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for item in object.values() {
            T::validate_json(item)?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventsLatestArgs {
    #[serde(rename = "actorId")]
    pub actor_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventsPublishArgs {
    pub payload: EventPayload,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventDoc {
    #[serde(rename = "actorId")]
    pub actor_id: String,
    pub payload: EventPayload,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventPayloadCreated {
    #[serde(rename = "targetId")]
    pub target_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EventPayloadDeleted {
    pub reason: Option<String>,
    #[serde(rename = "targetId")]
    pub target_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum EventPayload {
    #[serde(rename = "created")]
    Created(EventPayloadCreated),
    #[serde(rename = "deleted")]
    Deleted(EventPayloadDeleted),
}

pub type EventsLatestReturn = Option<Event>;
pub type EventsPublishReturn = String;
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Event {
    pub _id: String,
    #[serde(rename = "actorId")]
    pub actor_id: String,
    pub payload: EventPayload,
}

impl ConvexEncode for EventsLatestArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("actorId".to_string(), self.actor_id.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for EventsPublishArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("payload".to_string(), self.payload.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for EventDoc {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("actorId".to_string(), self.actor_id.to_convex_value());
        map.insert("payload".to_string(), self.payload.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for EventPayloadCreated {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("targetId".to_string(), self.target_id.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for EventPayloadDeleted {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        if let Some(value) = &self.reason {
            map.insert("reason".to_string(), value.to_convex_value());
        }
        map.insert("targetId".to_string(), self.target_id.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for EventPayload {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            EventPayload::Created(data) => {
                let mut map = BTreeMap::new();
                map.insert("kind".to_string(), ConvexValue::String("created".to_string()));
                map.insert("targetId".to_string(), data.target_id.to_convex_value());
                ConvexValue::Object(map)
            }
            EventPayload::Deleted(data) => {
                let mut map = BTreeMap::new();
                map.insert("kind".to_string(), ConvexValue::String("deleted".to_string()));
                if let Some(value) = &data.reason {
                    map.insert("reason".to_string(), value.to_convex_value());
                }
                map.insert("targetId".to_string(), data.target_id.to_convex_value());
                ConvexValue::Object(map)
            }
        }
    }
}

impl ConvexEncode for Event {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("_id".to_string(), self._id.to_convex_value());
        map.insert("actorId".to_string(), self.actor_id.to_convex_value());
        map.insert("payload".to_string(), self.payload.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl sealed::Sealed for EventsLatestArgs {}

impl sealed::Sealed for EventsPublishArgs {}

impl JsonValidate for EventsLatestArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "actorId" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("actorId") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: actorId"));
        }
        Ok(())
    }
}

impl JsonValidate for EventsPublishArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "payload" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("payload") {
            <EventPayload as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: payload"));
        }
        Ok(())
    }
}

impl JsonValidate for EventDoc {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "actorId" => {}
                "payload" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("actorId") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: actorId"));
        }
        if let Some(field_value) = object.get("payload") {
            <EventPayload as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: payload"));
        }
        Ok(())
    }
}

impl JsonValidate for EventPayloadCreated {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "targetId" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("targetId") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: targetId"));
        }
        Ok(())
    }
}

impl JsonValidate for EventPayloadDeleted {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "reason" => {}
                "targetId" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("reason") {
            if field_value.is_null() {
                return Err(ConvexTypeError::new("optional field 'reason' must be omitted, not null"));
            }
            <String as JsonValidate>::validate_json(field_value)?;
        }
        if let Some(field_value) = object.get("targetId") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: targetId"));
        }
        Ok(())
    }
}

impl JsonValidate for EventPayload {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        let tag = object
            .get("kind")
            .and_then(JsonValue::as_str)
            .ok_or_else(|| ConvexTypeError::new("missing discriminator"))?;
        match tag {
            "created" => {
                for key in object.keys() {
                    match key.as_str() {
                        "kind" => {}
                        "targetId" => {}
                        _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
                    }
                }
                if let Some(field_value) = object.get("targetId") {
                    <String as JsonValidate>::validate_json(field_value)?;
                } else {
                    return Err(ConvexTypeError::new("missing required field: targetId"));
                }
                Ok(())
            }
            "deleted" => {
                for key in object.keys() {
                    match key.as_str() {
                        "kind" => {}
                        "reason" => {}
                        "targetId" => {}
                        _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
                    }
                }
                if let Some(field_value) = object.get("reason") {
                    if field_value.is_null() {
                        return Err(ConvexTypeError::new("optional field 'reason' must be omitted, not null"));
                    }
                    <String as JsonValidate>::validate_json(field_value)?;
                }
                if let Some(field_value) = object.get("targetId") {
                    <String as JsonValidate>::validate_json(field_value)?;
                } else {
                    return Err(ConvexTypeError::new("missing required field: targetId"));
                }
                Ok(())
            }
            _ => Err(ConvexTypeError::new("unknown discriminator")),
        }
    }
}

impl JsonValidate for Event {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "_id" => {}
                "actorId" => {}
                "payload" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("_id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: _id"));
        }
        if let Some(field_value) = object.get("actorId") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: actorId"));
        }
        if let Some(field_value) = object.get("payload") {
            <EventPayload as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: payload"));
        }
        Ok(())
    }
}

