// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn events_latest(
        client: &ConvexClient,
        args: &EventsLatestArgs,
    ) -> Result<EventsLatestReturn, ConvexError> {
        client.query("events:latest", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn events_publish(
        client: &ConvexClient,
        args: &EventsPublishArgs,
    ) -> Result<EventsPublishReturn, ConvexError> {
        client.mutation("events:publish", args).await
    }

}

pub mod actions {
    use super::*;

}
