// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

fileprivate func encodeConvexArgs(_ args: [String: ConvexEncodable?]) throws -> [String: String] {
    try args.mapValues { value in
        try value?.convexEncode() ?? "null"
    }
}

fileprivate func convexCall<T: Decodable>(
    client: MobileConvexClient,
    path: String,
    args: [String: ConvexEncodable?],
    remoteCall: (String, [String: String]) async throws -> String
) async throws -> T {
    let encodedArgs = try encodeConvexArgs(args)
    let rawResult = try await remoteCall(path, encodedArgs)
    return try JSONDecoder().decode(T.self, from: Data(rawResult.utf8))
}

fileprivate actor ConvexSubscriptionState {
    private var handle: SubscriptionHandle?
    private var terminated = false

    func setHandle(_ handle: SubscriptionHandle) {
        if terminated {
            handle.cancel()
            return
        }
        self.handle = handle
    }

    func terminate() {
        terminated = true
        handle?.cancel()
        handle = nil
    }
}

fileprivate struct ConvexSubscriptionError: LocalizedError {
    let message: String
    let value: String?

    var errorDescription: String? { message }
}

fileprivate final class ConvexAsyncQuerySubscriber: QuerySubscriber {
    private let onErrorHandler: (String, String?) -> Void
    private let onUpdateHandler: (String) -> Void

    init(
        onError: @escaping (String, String?) -> Void,
        onUpdate: @escaping (String) -> Void
    ) {
        self.onErrorHandler = onError
        self.onUpdateHandler = onUpdate
    }

    func onError(message: String, value: String?) {
        onErrorHandler(message, value)
    }

    func onUpdate(value: String) {
        onUpdateHandler(value)
    }
}

fileprivate func convexSubscribe<T: Decodable>(
    client: MobileConvexClient,
    path: String,
    args: [String: ConvexEncodable?],
    yielding: T.Type
) -> AsyncThrowingStream<T, Error> {
    AsyncThrowingStream { continuation in
        let state = ConvexSubscriptionState()
        continuation.onTermination = { _ in
            Task { await state.terminate() }
        }
        let decoder = JSONDecoder()
        let subscriber = ConvexAsyncQuerySubscriber(
            onError: { message, value in
                continuation.finish(throwing: ConvexSubscriptionError(message: message, value: value))
            },
            onUpdate: { value in
                do {
                    let decoded = try decoder.decode(T.self, from: Data(value.utf8))
                    continuation.yield(decoded)
                } catch {
                    continuation.finish(throwing: error)
                }
            }
        )
        Task {
            do {
                let encodedArgs = try encodeConvexArgs(args)
                let handle = try await client.subscribe(name: path, args: encodedArgs, subscriber: subscriber)
                await state.setHandle(handle)
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}

enum ConvexQueries {
    static func adminUsersList<T: Decodable>(
        client: MobileConvexClient,
        args: AdminUsersListArgs
    ) -> AsyncThrowingStream<T, Error> {
        do {
            return convexSubscribe(client: client, path: "admin/users:list", args: try args.convexArgs(), yielding: T.self)
        } catch {
            return AsyncThrowingStream { continuation in
                continuation.finish(throwing: error)
            }
        }
    }

    static func adminUsersList<T: Decodable>(
        client: MobileConvexClient,
        limit: Double? = nil,
    ) -> AsyncThrowingStream<T, Error> {
        let args = AdminUsersListArgs(
            limit: limit,
        )
        return adminUsersList(client: client, args: args)
    }

    static func publicUsersList<T: Decodable>(
        client: MobileConvexClient,
        args: PublicUsersListArgs
    ) -> AsyncThrowingStream<T, Error> {
        do {
            return convexSubscribe(client: client, path: "public/users:list", args: try args.convexArgs(), yielding: T.self)
        } catch {
            return AsyncThrowingStream { continuation in
                continuation.finish(throwing: error)
            }
        }
    }

    static func publicUsersList<T: Decodable>(
        client: MobileConvexClient,
        cursor: String? = nil,
    ) -> AsyncThrowingStream<T, Error> {
        let args = PublicUsersListArgs(
            cursor: cursor,
        )
        return publicUsersList(client: client, args: args)
    }

}

enum ConvexMutations {
}

enum ConvexActions {
}
