// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct AdminUsersListArgs: ConvexCodable, Sendable {
    let limit: Double?
}


struct PublicUsersListArgs: ConvexCodable, Sendable {
    let cursor: String?
}


typealias AdminUsersListReturn = [User]

typealias PublicUsersListReturn = [String: String]

struct User: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let email: String

    var id: String { _id }
}


extension AdminUsersListArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        if let value = limit {
            args["limit"] = value
        }
        return args
    }
}


extension PublicUsersListArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        if let value = cursor {
            args["cursor"] = value
        }
        return args
    }
}


