// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn tasks_list(
        client: &ConvexClient,
        args: &TasksListArgs,
    ) -> Result<TasksListReturn, ConvexError> {
        client.query("tasks:list", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn tasks_apply_status_internal(
        client: &ConvexClient,
        args: &TasksApplyStatusInternalArgs,
    ) -> Result<TasksApplyStatusInternalReturn, ConvexError> {
        client.mutation("tasks:applyStatusInternal", args).await
    }

    pub async fn tasks_set_status(
        client: &ConvexClient,
        args: &TasksSetStatusArgs,
    ) -> Result<TasksSetStatusReturn, ConvexError> {
        client.mutation("tasks:setStatus", args).await
    }

}

pub mod actions {
    use super::*;

}
