// This file is @generated by hull. DO NOT EDIT.
#![allow(non_snake_case)]
#![allow(clippy::disallowed_types)]
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::collections::{BTreeMap, HashMap};
use crate::convex::ConvexValue;

#[derive(Debug, Clone)]
pub struct ConvexTypeError {
    message: String,
}
impl ConvexTypeError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
impl std::fmt::Display for ConvexTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
impl std::error::Error for ConvexTypeError {}

pub trait ConvexEncode {
    fn to_convex_value(&self) -> ConvexValue;
}

mod sealed {
    pub trait Sealed {}
}

pub trait ConvexArgs: sealed::Sealed + ConvexEncode {}
impl<T> ConvexArgs for T
where
    T: sealed::Sealed + ConvexEncode,
{}

pub trait JsonValidate: Sized {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError>;
    fn parse_json(value: &JsonValue) -> Result<Self, ConvexTypeError>
    where
        Self: for<'de> Deserialize<'de>,
    {
        Self::validate_json(value)?;
        serde_json::from_value(value.clone())
            .map_err(|err| ConvexTypeError::new(err.to_string()))
    }
}

fn json_value_to_convex(value: &JsonValue) -> ConvexValue {
    match value {
        JsonValue::Null => ConvexValue::Null,
        JsonValue::Bool(value) => ConvexValue::Bool(*value),
        JsonValue::Number(value) => ConvexValue::Float(value.as_f64().unwrap_or(0.0)),
        JsonValue::String(value) => ConvexValue::String(value.clone()),
        JsonValue::Array(values) => {
            ConvexValue::Array(values.iter().map(json_value_to_convex).collect())
        }
        JsonValue::Object(values) => ConvexValue::Object(
            values
                .iter()
                .map(|(key, value)| (key.clone(), json_value_to_convex(value)))
                .collect(),
        ),
    }
}

impl ConvexEncode for String {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::String(self.clone())
    }
}
impl ConvexEncode for bool {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Bool(*self)
    }
}
impl ConvexEncode for f64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Float(*self)
    }
}
impl ConvexEncode for i64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Int(*self)
    }
}
impl ConvexEncode for () {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Null
    }
}
impl ConvexEncode for JsonValue {
    fn to_convex_value(&self) -> ConvexValue {
        json_value_to_convex(self)
    }
}
impl<T> ConvexEncode for Option<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            Some(value) => value.to_convex_value(),
            None => ConvexValue::Null,
        }
    }
}
impl<T> ConvexEncode for Vec<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Array(self.iter().map(ConvexEncode::to_convex_value).collect())
    }
}
impl<T> ConvexEncode for HashMap<String, T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        for (key, value) in self {
            map.insert(key.clone(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl JsonValidate for String {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_string() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected string"))
        }
    }
}
impl JsonValidate for bool {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_boolean() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected bool"))
        }
    }
}
impl JsonValidate for f64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_number() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected number"))
        }
    }
}
impl JsonValidate for i64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.as_i64().is_some() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected int64"))
        }
    }
}
impl JsonValidate for () {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected null"))
        }
    }
}
impl JsonValidate for JsonValue {
    fn validate_json(_value: &JsonValue) -> Result<(), ConvexTypeError> {
        Ok(())
    }
}
impl<T> JsonValidate for Option<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            T::validate_json(value)
        }
    }
}
impl<T> JsonValidate for Vec<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let array = value
            .as_array()
            .ok_or_else(|| ConvexTypeError::new("expected array"))?;
        for item in array {
            T::validate_json(item)?;
        }
        Ok(())
    }
}
impl<T> JsonValidate for HashMap<String, T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for item in object.values() {
            T::validate_json(item)?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum TasksApplyStatusInternalArgsStatus {
    #[serde(rename = "todo")]
    Todo,
    #[serde(rename = "done")]
    Done,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TasksApplyStatusInternalArgs {
    pub id: String,
    pub status: TasksApplyStatusInternalArgsStatus,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum TasksListArgsStatus {
    #[serde(rename = "todo")]
    Todo,
    #[serde(rename = "done")]
    Done,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TasksListArgs {
    pub status: TasksListArgsStatus,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum TasksSetStatusArgsStatus {
    #[serde(rename = "todo")]
    Todo,
    #[serde(rename = "done")]
    Done,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TasksSetStatusArgs {
    pub id: String,
    pub status: TasksSetStatusArgsStatus,
}

pub type TasksApplyStatusInternalReturn = String;
pub type TasksListReturn = Vec<Task>;
pub type TasksSetStatusReturn = ();
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Task {
    pub _id: String,
    pub name: String,
    pub visibility: Visibility,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum Visibility {
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "shared")]
    Shared,
}

impl ConvexEncode for TasksApplyStatusInternalArgsStatus {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            TasksApplyStatusInternalArgsStatus::Todo => ConvexValue::String("todo".to_string()),
            TasksApplyStatusInternalArgsStatus::Done => ConvexValue::String("done".to_string()),
        }
    }
}

impl ConvexEncode for TasksApplyStatusInternalArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("id".to_string(), self.id.to_convex_value());
        map.insert("status".to_string(), self.status.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for TasksListArgsStatus {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            TasksListArgsStatus::Todo => ConvexValue::String("todo".to_string()),
            TasksListArgsStatus::Done => ConvexValue::String("done".to_string()),
        }
    }
}

impl ConvexEncode for TasksListArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("status".to_string(), self.status.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for TasksSetStatusArgsStatus {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            TasksSetStatusArgsStatus::Todo => ConvexValue::String("todo".to_string()),
            TasksSetStatusArgsStatus::Done => ConvexValue::String("done".to_string()),
        }
    }
}

impl ConvexEncode for TasksSetStatusArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("id".to_string(), self.id.to_convex_value());
        map.insert("status".to_string(), self.status.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for Task {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("_id".to_string(), self._id.to_convex_value());
        map.insert("name".to_string(), self.name.to_convex_value());
        map.insert("visibility".to_string(), self.visibility.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for Visibility {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            Visibility::Private => ConvexValue::String("private".to_string()),
            Visibility::Shared => ConvexValue::String("shared".to_string()),
        }
    }
}

impl sealed::Sealed for TasksListArgs {}

impl sealed::Sealed for TasksSetStatusArgs {}

impl sealed::Sealed for TasksApplyStatusInternalArgs {}

impl JsonValidate for TasksApplyStatusInternalArgsStatus {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let value = value.as_str().ok_or_else(|| ConvexTypeError::new("expected string"))?;
        match value {
            "todo" => Ok(()),
            "done" => Ok(()),
            _ => Err(ConvexTypeError::new("invalid enum value")),
        }
    }
}

impl JsonValidate for TasksApplyStatusInternalArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "id" => {}
                "status" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: id"));
        }
        if let Some(field_value) = object.get("status") {
            <TasksApplyStatusInternalArgsStatus as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: status"));
        }
        Ok(())
    }
}

impl JsonValidate for TasksListArgsStatus {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let value = value.as_str().ok_or_else(|| ConvexTypeError::new("expected string"))?;
        match value {
            "todo" => Ok(()),
            "done" => Ok(()),
            _ => Err(ConvexTypeError::new("invalid enum value")),
        }
    }
}

impl JsonValidate for TasksListArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "status" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("status") {
            <TasksListArgsStatus as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: status"));
        }
        Ok(())
    }
}

impl JsonValidate for TasksSetStatusArgsStatus {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let value = value.as_str().ok_or_else(|| ConvexTypeError::new("expected string"))?;
        match value {
            "todo" => Ok(()),
            "done" => Ok(()),
            _ => Err(ConvexTypeError::new("invalid enum value")),
        }
    }
}

impl JsonValidate for TasksSetStatusArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "id" => {}
                "status" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: id"));
        }
        if let Some(field_value) = object.get("status") {
            <TasksSetStatusArgsStatus as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: status"));
        }
        Ok(())
    }
}

impl JsonValidate for Task {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "_id" => {}
                "name" => {}
                "visibility" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("_id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: _id"));
        }
        if let Some(field_value) = object.get("name") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: name"));
        }
        if let Some(field_value) = object.get("visibility") {
            <Visibility as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: visibility"));
        }
        Ok(())
    }
}

impl JsonValidate for Visibility {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let value = value.as_str().ok_or_else(|| ConvexTypeError::new("expected string"))?;
        match value {
            "private" => Ok(()),
            "shared" => Ok(()),
            _ => Err(ConvexTypeError::new("invalid enum value")),
        }
    }
}

