// This file is @generated by hull. DO NOT EDIT.
#![allow(non_snake_case)]
#![allow(clippy::disallowed_types)]
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::collections::{BTreeMap, HashMap};
use crate::convex::ConvexValue;

#[derive(Debug, Clone)]
pub struct ConvexTypeError {
    message: String,
}
impl ConvexTypeError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
impl std::fmt::Display for ConvexTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
impl std::error::Error for ConvexTypeError {}

pub trait ConvexEncode {
    fn to_convex_value(&self) -> ConvexValue;
}

mod sealed {
    pub trait Sealed {}
}

pub trait ConvexArgs: sealed::Sealed + ConvexEncode {}
impl<T> ConvexArgs for T
where
    T: sealed::Sealed + ConvexEncode,
{}

pub trait JsonValidate: Sized {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError>;
    fn parse_json(value: &JsonValue) -> Result<Self, ConvexTypeError>
    where
        Self: for<'de> Deserialize<'de>,
    {
        Self::validate_json(value)?;
        serde_json::from_value(value.clone())
            .map_err(|err| ConvexTypeError::new(err.to_string()))
    }
}

fn json_value_to_convex(value: &JsonValue) -> ConvexValue {
    match value {
        JsonValue::Null => ConvexValue::Null,
        JsonValue::Bool(value) => ConvexValue::Bool(*value),
        JsonValue::Number(value) => ConvexValue::Float(value.as_f64().unwrap_or(0.0)),
        JsonValue::String(value) => ConvexValue::String(value.clone()),
        JsonValue::Array(values) => {
            ConvexValue::Array(values.iter().map(json_value_to_convex).collect())
        }
        JsonValue::Object(values) => ConvexValue::Object(
            values
                .iter()
                .map(|(key, value)| (key.clone(), json_value_to_convex(value)))
                .collect(),
        ),
    }
}

impl ConvexEncode for String {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::String(self.clone())
    }
}
impl ConvexEncode for bool {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Bool(*self)
    }
}
impl ConvexEncode for f64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Float(*self)
    }
}
impl ConvexEncode for i64 {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Int(*self)
    }
}
impl ConvexEncode for () {
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Null
    }
}
impl ConvexEncode for JsonValue {
    fn to_convex_value(&self) -> ConvexValue {
        json_value_to_convex(self)
    }
}
impl<T> ConvexEncode for Option<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            Some(value) => value.to_convex_value(),
            None => ConvexValue::Null,
        }
    }
}
impl<T> ConvexEncode for Vec<T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        ConvexValue::Array(self.iter().map(ConvexEncode::to_convex_value).collect())
    }
}
impl<T> ConvexEncode for HashMap<String, T>
where
    T: ConvexEncode,
{
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        for (key, value) in self {
            map.insert(key.clone(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl JsonValidate for String {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_string() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected string"))
        }
    }
}
impl JsonValidate for bool {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_boolean() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected bool"))
        }
    }
}
impl JsonValidate for f64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_number() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected number"))
        }
    }
}
impl JsonValidate for i64 {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.as_i64().is_some() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected int64"))
        }
    }
}
impl JsonValidate for () {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            Err(ConvexTypeError::new("expected null"))
        }
    }
}
impl JsonValidate for JsonValue {
    fn validate_json(_value: &JsonValue) -> Result<(), ConvexTypeError> {
        Ok(())
    }
}
impl<T> JsonValidate for Option<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        if value.is_null() {
            Ok(())
        } else {
            T::validate_json(value)
        }
    }
}
impl<T> JsonValidate for Vec<T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let array = value
            .as_array()
            .ok_or_else(|| ConvexTypeError::new("expected array"))?;
        for item in array {
            T::validate_json(item)?;
        }
        Ok(())
    }
}
impl<T> JsonValidate for HashMap<String, T>
where
    T: JsonValidate,
{
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for item in object.values() {
            T::validate_json(item)?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum AccountStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "disabled")]
    Disabled,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Account {
    pub _id: String,
    #[serde(rename = "createdAt")]
    pub created_at: f64,
    pub handle: String,
    pub name: String,
    pub status: AccountStatus,
    pub tags: Vec<String>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<f64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AccountsByHandleArgs {
    pub handle: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AccountsDisableArgs {
    pub id: String,
    pub reason: Option<String>,
}

pub type AccountsByHandleReturn = Option<Account>;
pub type AccountsDisableReturn = String;
impl ConvexEncode for AccountStatus {
    fn to_convex_value(&self) -> ConvexValue {
        match self {
            AccountStatus::Active => ConvexValue::String("active".to_string()),
            AccountStatus::Disabled => ConvexValue::String("disabled".to_string()),
        }
    }
}

impl ConvexEncode for Account {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("_id".to_string(), self._id.to_convex_value());
        map.insert("createdAt".to_string(), self.created_at.to_convex_value());
        map.insert("handle".to_string(), self.handle.to_convex_value());
        map.insert("name".to_string(), self.name.to_convex_value());
        map.insert("status".to_string(), self.status.to_convex_value());
        map.insert("tags".to_string(), self.tags.to_convex_value());
        if let Some(value) = &self.updated_at {
            map.insert("updatedAt".to_string(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for AccountsByHandleArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("handle".to_string(), self.handle.to_convex_value());
        ConvexValue::Object(map)
    }
}

impl ConvexEncode for AccountsDisableArgs {
    fn to_convex_value(&self) -> ConvexValue {
        let mut map = BTreeMap::new();
        map.insert("id".to_string(), self.id.to_convex_value());
        if let Some(value) = &self.reason {
            map.insert("reason".to_string(), value.to_convex_value());
        }
        ConvexValue::Object(map)
    }
}

impl sealed::Sealed for AccountsByHandleArgs {}

impl sealed::Sealed for AccountsDisableArgs {}

impl JsonValidate for AccountStatus {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let value = value.as_str().ok_or_else(|| ConvexTypeError::new("expected string"))?;
        match value {
            "active" => Ok(()),
            "disabled" => Ok(()),
            _ => Err(ConvexTypeError::new("invalid enum value")),
        }
    }
}

impl JsonValidate for Account {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "_id" => {}
                "createdAt" => {}
                "handle" => {}
                "name" => {}
                "status" => {}
                "tags" => {}
                "updatedAt" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("_id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: _id"));
        }
        if let Some(field_value) = object.get("createdAt") {
            <f64 as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: createdAt"));
        }
        if let Some(field_value) = object.get("handle") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: handle"));
        }
        if let Some(field_value) = object.get("name") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: name"));
        }
        if let Some(field_value) = object.get("status") {
            <AccountStatus as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: status"));
        }
        if let Some(field_value) = object.get("tags") {
            <Vec<String> as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: tags"));
        }
        if let Some(field_value) = object.get("updatedAt") {
            if field_value.is_null() {
                return Err(ConvexTypeError::new("optional field 'updatedAt' must be omitted, not null"));
            }
            <f64 as JsonValidate>::validate_json(field_value)?;
        }
        Ok(())
    }
}

impl JsonValidate for AccountsByHandleArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "handle" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("handle") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: handle"));
        }
        Ok(())
    }
}

impl JsonValidate for AccountsDisableArgs {
    fn validate_json(value: &JsonValue) -> Result<(), ConvexTypeError> {
        let object = value
            .as_object()
            .ok_or_else(|| ConvexTypeError::new("expected object"))?;
        for key in object.keys() {
            match key.as_str() {
                "id" => {}
                "reason" => {}
                _ => return Err(ConvexTypeError::new(format!("unknown field: {}", key))),
            }
        }
        if let Some(field_value) = object.get("id") {
            <String as JsonValidate>::validate_json(field_value)?;
        } else {
            return Err(ConvexTypeError::new("missing required field: id"));
        }
        if let Some(field_value) = object.get("reason") {
            if field_value.is_null() {
                return Err(ConvexTypeError::new("optional field 'reason' must be omitted, not null"));
            }
            <String as JsonValidate>::validate_json(field_value)?;
        }
        Ok(())
    }
}

