// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn accounts_by_handle(
        client: &ConvexClient,
        args: &AccountsByHandleArgs,
    ) -> Result<AccountsByHandleReturn, ConvexError> {
        client.query("accounts:byHandle", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn accounts_disable(
        client: &ConvexClient,
        args: &AccountsDisableArgs,
    ) -> Result<AccountsDisableReturn, ConvexError> {
        client.mutation("accounts:disable", args).await
    }

}

pub mod actions {
    use super::*;

}
