use anyhow::Result;

use super::naming::rust_fn_name;
use super::ConvexFunctionKind;

#[derive(Clone, Debug)]
pub(super) struct RustFunctionDef {
    pub(super) module: String,
    pub(super) name: String,
    pub(super) kind: ConvexFunctionKind,
    pub(super) args_name: String,
    pub(super) return_name: String,
}

pub(super) fn generate_rust_api(
    defs: &[RustFunctionDef],
    client_module_path: &str,
    types_module_path: &str,
) -> Result<String> {
    let mut out = String::new();
    out.push_str("// This file is @generated by hull. DO NOT EDIT.\n");
    out.push_str("#![allow(clippy::disallowed_methods)]\n");
    out.push_str(&format!(
        "use {}::{{ConvexClient, ConvexError}};\n",
        client_module_path
    ));
    out.push_str(&format!("use {}::*;\n\n", types_module_path));

    let mut queries = Vec::new();
    let mut mutations = Vec::new();
    let mut actions = Vec::new();

    for def in defs {
        let func_name = format!("{}_{}", def.module, def.name);
        match def.kind {
            ConvexFunctionKind::Query => queries.push((func_name, def)),
            ConvexFunctionKind::Mutation => mutations.push((func_name, def)),
            ConvexFunctionKind::Action => actions.push((func_name, def)),
            ConvexFunctionKind::HttpAction => {}
        }
    }

    queries.sort_by(|a, b| a.0.cmp(&b.0));
    mutations.sort_by(|a, b| a.0.cmp(&b.0));
    actions.sort_by(|a, b| a.0.cmp(&b.0));

    out.push_str("pub mod queries {\n");
    out.push_str("    use super::*;\n\n");
    for (_, def) in &queries {
        let fn_name = rust_fn_name(&format!("{}_{}", def.module, def.name));
        out.push_str(&format!("    pub async fn {}(\n", fn_name,));
        out.push_str("        client: &ConvexClient,\n");
        out.push_str(&format!("        args: &{},\n", def.args_name));
        out.push_str(&format!(
            "    ) -> Result<{}, ConvexError> {{\n",
            def.return_name
        ));
        out.push_str(&format!(
            "        client.query(\"{}:{}\", args).await\n",
            def.module, def.name
        ));
        out.push_str("    }\n\n");
    }
    out.push_str("}\n\n");

    out.push_str("pub mod mutations {\n");
    out.push_str("    use super::*;\n\n");
    for (_, def) in &mutations {
        let fn_name = rust_fn_name(&format!("{}_{}", def.module, def.name));
        out.push_str(&format!("    pub async fn {}(\n", fn_name,));
        out.push_str("        client: &ConvexClient,\n");
        out.push_str(&format!("        args: &{},\n", def.args_name));
        out.push_str(&format!(
            "    ) -> Result<{}, ConvexError> {{\n",
            def.return_name
        ));
        out.push_str(&format!(
            "        client.mutation(\"{}:{}\", args).await\n",
            def.module, def.name
        ));
        out.push_str("    }\n\n");
    }
    out.push_str("}\n\n");

    out.push_str("pub mod actions {\n");
    out.push_str("    use super::*;\n\n");
    for (_, def) in &actions {
        let fn_name = rust_fn_name(&format!("{}_{}", def.module, def.name));
        out.push_str(&format!("    pub async fn {}(\n", fn_name,));
        out.push_str("        client: &ConvexClient,\n");
        out.push_str(&format!("        args: &{},\n", def.args_name));
        out.push_str(&format!(
            "    ) -> Result<{}, ConvexError> {{\n",
            def.return_name
        ));
        out.push_str(&format!(
            "        client.action(\"{}:{}\", args).await\n",
            def.module, def.name
        ));
        out.push_str("    }\n\n");
    }
    out.push_str("}\n");

    Ok(out)
}
