// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

enum AccountStatus: String, ConvexCodable, Sendable {
    case active = "active"
    case disabled = "disabled"
}


struct Account: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let createdAt: Double
    let handle: String
    let name: String
    let status: AccountStatus
    let tags: [String]
    let updatedAt: Double?

    var id: String { _id }
}


struct AccountsByHandleArgs: ConvexCodable, Sendable {
    let handle: String
}


struct AccountsDisableArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
    let reason: String?
}


typealias AccountsByHandleReturn = Account?

typealias AccountsDisableReturn = String

extension AccountsByHandleArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["handle"] = handle
        return args
    }
}


extension AccountsDisableArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        if let value = reason {
            args["reason"] = value
        }
        return args
    }
}


