// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

fileprivate func encodeConvexArgs(_ args: [String: ConvexEncodable?]) throws -> [String: String] {
    try args.mapValues { value in
        try value?.convexEncode() ?? "null"
    }
}

fileprivate func convexCall<T: Decodable>(
    client: MobileConvexClient,
    path: String,
    args: [String: ConvexEncodable?],
    remoteCall: (String, [String: String]) async throws -> String
) async throws -> T {
    let encodedArgs = try encodeConvexArgs(args)
    let rawResult = try await remoteCall(path, encodedArgs)
    return try JSONDecoder().decode(T.self, from: Data(rawResult.utf8))
}

fileprivate actor ConvexSubscriptionState {
    private var handle: SubscriptionHandle?
    private var terminated = false

    func setHandle(_ handle: SubscriptionHandle) {
        if terminated {
            handle.cancel()
            return
        }
        self.handle = handle
    }

    func terminate() {
        terminated = true
        handle?.cancel()
        handle = nil
    }
}

fileprivate struct ConvexSubscriptionError: LocalizedError {
    let message: String
    let value: String?

    var errorDescription: String? { message }
}

fileprivate final class ConvexAsyncQuerySubscriber<T: Decodable>: QuerySubscriber {
    private let decoder: JSONDecoder
    private let continuation: AsyncThrowingStream<T, Error>.Continuation

    init(decoder: JSONDecoder, continuation: AsyncThrowingStream<T, Error>.Continuation) {
        self.decoder = decoder
        self.continuation = continuation
    }

    func onError(message: String, value: String?) {
        continuation.finish(throwing: ConvexSubscriptionError(message: message, value: value))
    }

    func onUpdate(value: String) {
        do {
            let decoded = try decoder.decode(T.self, from: Data(value.utf8))
            continuation.yield(decoded)
        } catch {
            continuation.finish(throwing: error)
        }
    }
}

fileprivate func convexSubscribe<T: Decodable>(
    client: MobileConvexClient,
    path: String,
    args: [String: ConvexEncodable?],
    yielding: T.Type
) -> AsyncThrowingStream<T, Error> {
    AsyncThrowingStream { continuation in
        let state = ConvexSubscriptionState()
        continuation.onTermination = { _ in
            Task { await state.terminate() }
        }
        let subscriber = ConvexAsyncQuerySubscriber(decoder: JSONDecoder(), continuation: continuation)
        Task {
            do {
                let encodedArgs = try encodeConvexArgs(args)
                let handle = try await client.subscribe(name: path, args: encodedArgs, subscriber: subscriber)
                await state.setHandle(handle)
            } catch {
                continuation.finish(throwing: error)
            }
        }
    }
}

enum ConvexQueries {
    static func accountsByHandle<T: Decodable>(
        client: MobileConvexClient,
        args: AccountsByHandleArgs
    ) -> AsyncThrowingStream<T, Error> {
        do {
            return convexSubscribe(client: client, path: "accounts:byHandle", args: try args.convexArgs(), yielding: T.self)
        } catch {
            return AsyncThrowingStream { continuation in
                continuation.finish(throwing: error)
            }
        }
    }

    static func accountsByHandle<T: Decodable>(
        client: MobileConvexClient,
        handle: String,
    ) -> AsyncThrowingStream<T, Error> {
        let args = AccountsByHandleArgs(
            handle: handle,
        )
        return accountsByHandle(client: client, args: args)
    }

}

enum ConvexMutations {
    static func accountsDisable<T: Decodable>(
        client: MobileConvexClient,
        args: AccountsDisableArgs
    ) async throws -> T {
        try await convexCall(client: client, path: "accounts:disable", args: try args.convexArgs(), remoteCall: client.mutation)
    }

    static func accountsDisable<T: Decodable>(
        client: MobileConvexClient,
        id: String,
        reason: String? = nil,
    ) async throws -> T {
        let args = AccountsDisableArgs(
            id: id,
            reason: reason,
        )
        return try await accountsDisable(client: client, args: args)
    }

}

enum ConvexActions {
}
