// This file is @generated by hull. DO NOT EDIT.
#![allow(clippy::disallowed_methods)]
use crate::convex::{ConvexClient, ConvexError};
use crate::generated::convex_types::*;

pub mod queries {
    use super::*;

    pub async fn admin_users_get_by_id(
        client: &ConvexClient,
        args: &AdminUsersGetByIDArgs,
    ) -> Result<AdminUsersGetByIDReturn, ConvexError> {
        client.query("admin/users:getById", args).await
    }

    pub async fn messages_list(
        client: &ConvexClient,
        args: &MessagesListArgs,
    ) -> Result<MessagesListReturn, ConvexError> {
        client.query("messages:list", args).await
    }

}

pub mod mutations {
    use super::*;

    pub async fn messages_create(
        client: &ConvexClient,
        args: &MessagesCreateArgs,
    ) -> Result<MessagesCreateReturn, ConvexError> {
        client.mutation("messages:create", args).await
    }

}

pub mod actions {
    use super::*;

}
