// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

struct AdminUsersGetByIDArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
}


struct MessagesCreateArgs: ConvexCodable, Sendable {
    let authorId: String
    let body: String
}


struct MessagesListArgs: ConvexCodable, Sendable {
    let limit: Double?
}


struct Message: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let authorId: String
    let body: String
    let tags: [String]

    var id: String { _id }
}


typealias AdminUsersGetByIDReturn = User?

typealias MessagesCreateReturn = String

typealias MessagesListReturn = [Message]

enum UserRole: String, ConvexCodable, Sendable {
    case admin = "admin"
    case member = "member"
}


struct User: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let email: String
    let name: String
    let role: UserRole

    var id: String { _id }
}


extension AdminUsersGetByIDArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        return args
    }
}


extension MessagesListArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        if let value = limit {
            args["limit"] = value
        }
        return args
    }
}


extension MessagesCreateArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["authorId"] = authorId
        args["body"] = body
        return args
    }
}


