// swift-format-ignore-file
// This file is @generated by hull. DO NOT EDIT.
import Foundation
@preconcurrency import ConvexMobile

enum TasksApplyStatusInternalArgsStatus: String, ConvexCodable, Sendable {
    case todo = "todo"
    case done = "done"
}


struct TasksApplyStatusInternalArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
    let status: TasksApplyStatusInternalArgsStatus
}


enum TasksListArgsStatus: String, ConvexCodable, Sendable {
    case todo = "todo"
    case done = "done"
}


struct TasksListArgs: ConvexCodable, Sendable {
    let status: TasksListArgsStatus
}


enum TasksSetStatusArgsStatus: String, ConvexCodable, Sendable {
    case todo = "todo"
    case done = "done"
}


struct TasksSetStatusArgs: ConvexCodable, Identifiable, Sendable {
    let id: String
    let status: TasksSetStatusArgsStatus
}


typealias TasksApplyStatusInternalReturn = String

typealias TasksListReturn = [Task]

typealias TasksSetStatusReturn = JSONValue

struct Task: ConvexCodable, Identifiable, Sendable {
    let _id: String
    let name: String
    let visibility: Visibility

    var id: String { _id }
}


enum Visibility: String, ConvexCodable, Sendable {
    case private = "private"
    case shared = "shared"
}


extension TasksListArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["status"] = status
        return args
    }
}


extension TasksSetStatusArgs {
    func convexArgs() throws -> [String: ConvexEncodable?] {
        var args: [String: ConvexEncodable?] = [:]
        args["id"] = id
        args["status"] = status
        return args
    }
}


